In [11]:
import pandas as pd

In [12]:
df = pd.read_csv('D:/ds/leopard-challenge/train.csv')

In [13]:
df[:50]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,id
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0,34302
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0,33247
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0,31886
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,1.0,94.0,NaN,NaN,Yarra City Council,-37.7969,144.9969,Northern Metropolitan,4019.0,18999
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,2.0,120.0,142.0,2014.0,Yarra City Council,-37.8072,144.9941,Northern Metropolitan,4019.0,16809
5,Abbotsford,129 Charles St,2,h,941000.0,S,Jellis,7/05/2016,2.5,3067.0,...,0.0,181.0,NaN,NaN,Yarra City Council,-37.8041,144.9953,Northern Metropolitan,4019.0,33671
6,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,...,0.0,245.0,210.0,1910.0,Yarra City Council,-37.8024,144.9993,Northern Metropolitan,4019.0,18292
7,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,8/10/2016,2.5,3067.0,...,2.0,256.0,107.0,1890.0,Yarra City Council,-37.8060,144.9954,Northern Metropolitan,4019.0,11545
8,Abbotsford,217 Langridge St,3,h,1000000.0,S,Jellis,8/10/2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,Yarra City Council,NaN,NaN,Northern Metropolitan,4019.0,3742
9,Abbotsford,18a Mollison St,2,t,745000.0,S,Jellis,8/10/2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,Yarra City Council,NaN,NaN,Northern Metropolitan,4019.0,3250
10,Abbotsford,6/241 Nicholson St,1,u,300000.0,S,Biggin,8/10/2016,2.5,3067.0,...,1.0,0.0,NaN,NaN,Yarra City Council,-37.8008,144.9973,Northern Metropolitan,4019.0,26686
11,Abbotsford,10 Valiant St,2,h,1097000.0,S,Biggin,8/10/2016,2.5,3067.0,...,2.0,220.0,75.0,1900.0,Yarra City Council,-37.8010,144.9989,Northern Metropolitan,4019.0,18730
12,Abbotsford,403/609 Victoria St,2,u,542000.0,S,Dingle,8/10/2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,Yarra City Council,NaN,NaN,Northern Metropolitan,4019.0,5259
13,Abbotsford,25/84 Trenerry Cr,2,u,760000.0,SP,Biggin,10/12/2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,Yarra City Council,NaN,NaN,Northern Metropolitan,4019.0,31466
14,Abbotsford,106/119 Turner St,1,u,481000.0,SP,Purplebricks,10/12/2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,Yarra City Council,NaN,NaN,Northern Metropolitan,4019.0,15478
15,Abbotsford,411/8 Grosvenor St,2,u,700000.0,VB,Jellis,12/11/2016,2.5,3067.0,...,1.0,0.0,NaN,NaN,Yarra City Council,-37.8110,145.0067,Northern Metropolitan,4019.0,1944
16,Abbotsford,40 Nicholson St,3,h,1350000.0,VB,Nelson,12/11/2016,2.5,3067.0,...,2.0,214.0,190.0,2005.0,Yarra City Council,-37.8085,144.9964,Northern Metropolitan,4019.0,22774
17,Abbotsford,123/56 Nicholson St,2,u,750000.0,S,Biggin,12/11/2016,2.5,3067.0,...,1.0,0.0,94.0,2009.0,Yarra City Council,-37.8078,144.9965,Northern Metropolitan,4019.0,11027
18,Abbotsford,22 Park St,4,h,1985000.0,S,Biggin,12/11/2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,Yarra City Council,-37.8084,144.9942,Northern Metropolitan,4019.0,15408
19,Abbotsford,13/84 Trenerry Cr,1,u,500000.0,S,Biggin,12/11/2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,Yarra City Council,NaN,NaN,Northern Metropolitan,4019.0,33210
20,Abbotsford,45 William St,2,h,1172500.0,S,Biggin,13/08/2016,2.5,3067.0,...,1.0,195.0,NaN,NaN,Yarra City Council,-37.8084,144.9973,Northern Metropolitan,4019.0,5311
21,Abbotsford,7/20 Abbotsford St,1,u,441000.0,SP,Greg,14/05/2016,2.5,3067.0,...,1.0,0.0,NaN,NaN,Yarra City Council,-37.8016,144.9988,Northern Metropolitan,4019.0,6073
22,Abbotsford,16 William St,2,h,1310000.0,S,Jellis,15/10/2016,2.5,3067.0,...,2.0,238.0,97.0,1890.0,Yarra City Council,-37.8090,144.9976,Northern Metropolitan,4019.0,28372
23,Abbotsford,42 Henry St,3,h,1200000.0,S,Jellis,16/07/2016,2.5,3067.0,...,1.0,113.0,110.0,1880.0,Yarra City Council,-37.8056,144.9930,Northern Metropolitan,4019.0,28719
24,Abbotsford,250 Langridge St,2,t,847000.0,S,Jellis,16/07/2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,Yarra City Council,NaN,NaN,Northern Metropolitan,4019.0,20243
25,Abbotsford,78 Yarra St,3,h,1176500.0,S,LITTLE,16/07/2016,2.5,3067.0,...,1.0,138.0,105.0,1890.0,Yarra City Council,-37.8021,144.9965,Northern Metropolitan,4019.0,10312
26,Abbotsford,196 Nicholson St,3,h,955000.0,S,Collins,17/09/2016,2.5,3067.0,...,0.0,183.0,NaN,NaN,Yarra City Council,-37.8022,144.9975,Northern Metropolitan,4019.0,12148
27,Abbotsford,42 Valiant St,2,h,890000.0,S,Biggin,17/09/2016,2.5,3067.0,...,1.0,150.0,73.0,1985.0,Yarra City Council,-37.8011,145.0004,Northern Metropolitan,4019.0,33817
28,Abbotsford,3/72 Charles St,4,h,1330000.0,PI,Kay,18/03/2017,2.5,3067.0,...,2.0,780.0,135.0,1900.0,Yarra City Council,-37.8073,144.9952,Northern Metropolitan,4019.0,31903
29,Abbotsford,13/11 Nicholson St,3,t,900000.0,S,Beller,18/03/2017,2.5,3067.0,...,2.0,0.0,NaN,2010.0,Yarra City Council,-37.8093,144.9959,Northern Metropolitan,4019.0,14059
30,Abbotsford,138/56 Nicholson St,3,u,1090000.0,S,Jellis,18/03/2017,2.5,3067.0,...,2.0,4290.0,27.0,NaN,Yarra City Council,-37.8078,144.9965,Northern Metropolitan,4019.0,12399
31,Abbotsford,6/219 Nicholson St,2,u,500000.0,S,Collins,18/06/2016,2.5,3067.0,...,1.0,0.0,60.0,1970.0,Yarra City Council,-37.8015,144.9972,Northern Metropolitan,4019.0,19366
32,Abbotsford,52a William St,2,h,1100000.0,PI,Biggin,18/06/2016,2.5,3067.0,...,1.0,124.0,135.0,2013.0,Yarra City Council,-37.8079,144.9977,Northern Metropolitan,4019.0,20964
33,Abbotsford,49 Park St,2,h,1315000.0,S,Marshall,19/11/2016,2.5,3067.0,...,0.0,147.0,85.0,1900.0,Yarra City Council,-37.8080,144.9940,Northern Metropolitan,4019.0,17455
34,Abbotsford,65/80 Trenerry Cr,1,u,480000.0,S,Biggin,19/11/2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,Yarra City Council,NaN,NaN,Northern Metropolitan,4019.0,25171
35,Abbotsford,119/52 Nicholson St,1,u,423500.0,S,hockingstuart,22/05/2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,Yarra City Council,NaN,NaN,Northern Metropolitan,4019.0,5774
36,Abbotsford,5/20 Abbotsford St,1,u,426000.0,SP,Greg,22/08/2016,2.5,3067.0,...,1.0,0.0,NaN,NaN,Yarra City Council,-37.8016,144.9988,Northern Metropolitan,4019.0,15227
37,Abbotsford,48 Abbotsford St,3,h,1447500.0,PI,Nelson,22/08/2016,2.5,3067.0,...,1.0,166.0,174.0,2012.0,Yarra City Council,-37.8017,145.0001,Northern Metropolitan,4019.0,13905
38,Abbotsford,116/56 Nicholson St,1,u,457000.0,S,Jellis,22/08/2016,2.5,3067.0,...,1.0,0.0,50.0,NaN,Yarra City Council,-37.8078,144.9965,Northern Metropolitan,4019.0,7207
39,Abbotsford,159 Park St,2,h,1135000.0,S,Nelson,22/08/2016,2.5,3067.0,...,2.0,98.0,128.0,1920.0,Yarra City Council,-37.8005,144.9952,Northern Metropolitan,4019.0,4525
40,Abbotsford,49/84 Trenerry Cr,2,h,700000.0,S,Biggin,23/04/2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,Yarra City Council,NaN,NaN,Northern Metropolitan,4019.0,12588
41,Abbotsford,31 Turner St,4,h,1542000.0,S,Collins,24/09/2016,2.5,3067.0,...,1.0,0.0,NaN,NaN,Yarra City Council,-37.7994,144.9965,Northern Metropolitan,4019.0,16039
42,Abbotsford,17/1 Abbot St,3,t,962000.0,SP,Jellis,25/02/2017,2.5,3067.0,...,NaN,NaN,NaN,NaN,Yarra City Council,-37.7972,144.9969,Northern Metropolitan,4019.0,26888
43,Abbotsford,166 Gipps St,3,h,1290000.0,S,Biggin,25/02/2017,2.5,3067.0,...,2.0,147.0,18.0,NaN,Yarra City Council,-37.8050,144.9943,Northern Metropolitan,4019.0,21847
44,Abbotsford,60 Stafford St,3,h,1290000.0,S,Biggin,25/02/2017,2.5,3067.0,...,1.0,168.0,124.0,1950.0,Yarra City Council,-37.8007,144.9958,Northern Metropolitan,4019.0,9116
45,Abbotsford,11/205 Gipps St,1,u,470000.0,S,Nelson,26/07/2016,2.5,3067.0,...,1.0,0.0,50.0,2013.0,Yarra City Council,-37.8055,144.9961,Northern Metropolitan,4019.0,25529
46,Abbotsford,47 Studley St,2,h,1180000.0,S,Jellis,27/11/2016,2.5,3067.0,...,0.0,162.0,91.0,1900.0,Yarra City Council,-37.8016,144.9956,Northern Metropolitan,4019.0,8652
47,Abbotsford,45 Yarra St,3,h,1195000.0,SP,Jellis,27/11/2016,2.5,3067.0,...,1.0,120.0,128.0,1998.0,Yarra City Council,-37.8022,144.9954,Northern Metropolitan,4019.0,18205
48,Abbotsford,200 Nicholson St,2,h,1012500.0,S,Nelson,28/05/2016,2.5,3067.0,...,0.0,182.0,82.0,1900.0,Yarra City Council,-37.8021,144.9976,Northern Metropolitan,4019.0,26620
49,Abbotsford,82/84 Trenerry Cr,2,u,970000.0,SP,Biggin,28/05/2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,Yarra City Council,NaN,NaN,Northern Metropolitan,4019.0,23881

In [14]:
df.shape

(18373, 22)

# Выполняем предобработку данных и избавляемся от NaN

In [15]:
df.isna().mean()

Suburb           0.000000
Address          0.000000
Rooms            0.000000
Type             0.000000
Price            0.000000
Method           0.000000
SellerG          0.000000
Date             0.000000
Distance         0.000000
Postcode         0.000000
Bedroom2         0.188755
Bathroom         0.188864
Car              0.194579
Landsize         0.260926
BuildingArea     0.578185
YearBuilt        0.513199
CouncilArea      0.000054
Lattitude        0.181353
Longtitude       0.181353
Regionname       0.000054
Propertycount    0.000054
id               0.000000
dtype: float64

In [16]:
sp = pd.Series(df.columns).tolist()

In [17]:
sp

['Suburb',
 'Address',
 'Rooms',
 'Type',
 'Price',
 'Method',
 'SellerG',
 'Date',
 'Distance',
 'Postcode',
 'Bedroom2',
 'Bathroom',
 'Car',
 'Landsize',
 'BuildingArea',
 'YearBuilt',
 'CouncilArea',
 'Lattitude',
 'Longtitude',
 'Regionname',
 'Propertycount',
 'id']

In [18]:
for i in sp:
    df[i] = df[i].fillna(df[i].mode()[0])

In [19]:
df.isna().mean()

Suburb           0.0
Address          0.0
Rooms            0.0
Type             0.0
Price            0.0
Method           0.0
SellerG          0.0
Date             0.0
Distance         0.0
Postcode         0.0
Bedroom2         0.0
Bathroom         0.0
Car              0.0
Landsize         0.0
BuildingArea     0.0
YearBuilt        0.0
CouncilArea      0.0
Lattitude        0.0
Longtitude       0.0
Regionname       0.0
Propertycount    0.0
id               0.0
dtype: float64

In [20]:
df.shape

(18373, 22)

# Начинаем сборку модели машинного обучения

In [21]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(df,train_size=0.6,random_state=42)
val, test = train_test_split(test,train_size=0.5,random_state=42)

In [22]:
train.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount', 'id'],
      dtype='object')

In [23]:
train.select_dtypes(include='object')

,Suburb,Address,Type,Method,SellerG,Date,CouncilArea,Regionname
7487,St Kilda,6/22 Charnwood Cr,u,VB,Hodges,28/05/2016,Port Phillip City Council,Southern Metropolitan
14244,Tarneit,4 Welford St,h,SP,Reliance,12/08/2017,Wyndham City Council,Western Metropolitan
7621,Sunshine,17 Leonard St,h,S,Douglas,18/06/2016,Brimbank City Council,Western Metropolitan
13334,Nunawading,3/7 Lilian St,t,S,Fletchers,27/05/2017,Manningham City Council,Eastern Metropolitan
9412,Albert Park,21 Finlay St,h,S,Marshall,13/05/2017,Port Phillip City Council,Southern Metropolitan
...,...,...,...,...,...,...,...,...
11284,Narre Warren,28 Murdoch Av,h,SP,O'Brien,1/07/2017,Casey City Council,South-Eastern Metropolitan
11964,Armadale,504 Orrong Rd,h,VB,Kay,17/06/2017,Stonnington City Council,Southern Metropolitan
5390,Newport,33 Oxford St,h,S,Williams,7/11/2016,Hobsons Bay City Council,Western Metropolitan
860,Balwyn North,237a Balwyn Rd,h,PI,Appleby,16/04/2016,Boroondara City Council,Southern Metropolitan
15795,West Melbourne,4/593 Spencer St,u,S,MICM,3/09/2017,Melbourne City Council,Northern Metropolitan

In [25]:
X = ['Suburb', 'Rooms', 'Type', 'Method',
     'Distance', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 
     'CouncilArea', 'Regionname', 'Propertycount']

cat_features = ['Suburb','Type','Method','CouncilArea','Regionname']

y = ['Price']

In [26]:
from catboost import Pool

train_data = Pool(data=train[X],
                  label=train[y],
                  cat_features=cat_features,
                 )

valid_data = Pool(data=val[X],
                  label=val[y],
                  cat_features=cat_features
                 )

In [27]:
from catboost import CatBoostRegressor

In [107]:
parameters = {'cat_features': cat_features,
              'eval_metric': 'MAPE',
              'loss_function':'RMSE',
              'random_seed':42,
              'learning_rate':0.1,
              'verbose':100}

# Кросс-валидация подбора параметров

In [108]:
from catboost import cv

In [110]:
cv_data = cv(
    params = parameters,
    pool = train_data,
    fold_count=5,
    shuffle=True,
    partition_random_seed=0,
    stratified=False,
    verbose=False,
    early_stopping_rounds=200
)

Training on fold [0/5]

bestTest = 0.162618601
bestIteration = 999

Training on fold [1/5]

bestTest = 0.1603051837
bestIteration = 963

Training on fold [2/5]

bestTest = 0.1546245087
bestIteration = 971

Training on fold [3/5]

bestTest = 0.1666306091
bestIteration = 999

Training on fold [4/5]

bestTest = 0.1570191635
bestIteration = 940

In [111]:
cv_data.head()

,iterations,test-MAPE-mean,test-MAPE-std,train-MAPE-mean,train-MAPE-std,test-RMSE-mean,test-RMSE-std,train-RMSE-mean,train-RMSE-std
0,0,0.886133,0.002156,0.885994,0.001045,1.120633e+06,14682.262499,1.120182e+06,4498.590488
1,1,0.783598,0.001952,0.783166,0.002603,1.029412e+06,13864.937502,1.028974e+06,5900.919879
2,2,0.692150,0.002504,0.691962,0.003302,9.466604e+05,12911.206319,9.462445e+05,6134.761979
3,3,0.611713,0.003777,0.610905,0.005023,8.728349e+05,10689.678250,8.721461e+05,8269.483442
4,4,0.541121,0.003766,0.540319,0.004070,8.062289e+05,10080.087340,8.053689e+05,7505.398751

In [112]:
cv_data[cv_data['test-MAPE-mean'] == cv_data['test-MAPE-mean'].min()]

,iterations,test-MAPE-mean,test-MAPE-std,train-MAPE-mean,train-MAPE-std,test-RMSE-mean,test-RMSE-std,train-RMSE-mean,train-RMSE-std
999,999,0.160341,0.004608,0.128437,0.000845,280338.211353,14987.258195,196350.300038,1838.440244

In [113]:
model = CatBoostRegressor(**parameters)

In [114]:
model.fit(train_data, eval_set=valid_data)

0:	learn: 0.5026030	test: 0.4909703	best: 0.4909703 (0)	total: 52.7ms	remaining: 52.7s
100:	learn: 0.1766804	test: 0.1740280	best: 0.1740280 (100)	total: 5.53s	remaining: 49.2s
200:	learn: 0.1603146	test: 0.1638298	best: 0.1638263 (198)	total: 11.3s	remaining: 45s
300:	learn: 0.1530121	test: 0.1602397	best: 0.1601861 (297)	total: 17.1s	remaining: 39.6s
400:	learn: 0.1475055	test: 0.1580270	best: 0.1579452 (393)	total: 22.9s	remaining: 34.3s
500:	learn: 0.1437065	test: 0.1569538	best: 0.1569279 (496)	total: 28.8s	remaining: 28.7s
600:	learn: 0.1402169	test: 0.1561085	best: 0.1561048 (599)	total: 34.5s	remaining: 22.9s
700:	learn: 0.1372327	test: 0.1553054	best: 0.1553054 (700)	total: 40.3s	remaining: 17.2s
800:	learn: 0.1345779	test: 0.1547256	best: 0.1546965 (787)	total: 46.1s	remaining: 11.5s
900:	learn: 0.1326726	test: 0.1544869	best: 0.1544323 (873)	total: 51.9s	remaining: 5.7s
999:	learn: 0.1306655	test: 0.1540521	best: 0.1540001 (974)	total: 57.7s	remaining: 0us

bestTest = 0.1540001191
bestIteration = 974

Shrink model to first 975 iterations.

# Добавляем тестовый датасет

In [115]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error

def error(y_true,y_pred):
  print(mean_absolute_error(y_true,y_pred))
  print(mean_absolute_percentage_error(y_true,y_pred))

In [116]:
test['price_pred_all'] = model.predict(test[X])

In [117]:
error(test['Price'],test['price_pred_all'])

168750.94113942716
0.1605833242629532

# Обучаемся на всех данных

In [118]:
len(train)

11023

In [119]:
len(val)

3675

In [120]:
len(train) + len(val)

14698

In [122]:
train_full = pd.concat([train,val])

In [123]:
train_full = Pool(data=train_full[X],
                  label=train_full[y],
                  cat_features=cat_features,
                 )

In [124]:
model.fit(train_full)

0:	learn: 0.4982053	total: 57.3ms	remaining: 57.2s
100:	learn: 0.1725636	total: 6.09s	remaining: 54.2s
200:	learn: 0.1603085	total: 12s	remaining: 47.7s
300:	learn: 0.1541264	total: 18s	remaining: 41.8s
400:	learn: 0.1486693	total: 24s	remaining: 35.9s
500:	learn: 0.1457799	total: 30s	remaining: 29.9s
600:	learn: 0.1431527	total: 36.1s	remaining: 24s
700:	learn: 0.1403264	total: 42.2s	remaining: 18s
800:	learn: 0.1382877	total: 48.2s	remaining: 12s
900:	learn: 0.1362473	total: 54.1s	remaining: 5.94s
999:	learn: 0.1343565	total: 1m	remaining: 0us

In [125]:
test['price_pred_all_features_and_data'] = model.predict(test[X])

In [126]:
error(test['Price'],test['price_pred_all_features_and_data'])

167558.34775813064
0.16081300965155085

# Загружаем датасет для submission

In [127]:
test_new = pd.read_csv('D:/ds/leopard-challenge/test.csv')

In [128]:
test_new.shape

(8818, 21)

In [129]:
test_new.isna().mean()

Suburb           0.000000
Address          0.000000
Rooms            0.000000
Type             0.000000
Method           0.000000
SellerG          0.000000
Date             0.000000
Distance         0.000113
Postcode         0.000113
Bedroom2         0.335677
Bathroom         0.336131
Car              0.366977
Landsize         0.504990
BuildingArea     0.673169
YearBuilt        0.647086
CouncilArea      0.000227
Lattitude        0.330007
Longtitude       0.330007
Regionname       0.000227
Propertycount    0.000227
id               0.000000
dtype: float64

In [130]:
sp_test = pd.Series(test_new.columns).tolist()

for i in sp_test:
    test_new[i] = test_new[i].fillna(test_new[i].mode()[0])

In [131]:
test_new.isna().mean()

Suburb           0.0
Address          0.0
Rooms            0.0
Type             0.0
Method           0.0
SellerG          0.0
Date             0.0
Distance         0.0
Postcode         0.0
Bedroom2         0.0
Bathroom         0.0
Car              0.0
Landsize         0.0
BuildingArea     0.0
YearBuilt        0.0
CouncilArea      0.0
Lattitude        0.0
Longtitude       0.0
Regionname       0.0
Propertycount    0.0
id               0.0
dtype: float64

In [132]:
test_new.shape

(8818, 21)

In [133]:
test_new.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Method', 'SellerG', 'Date',
       'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car', 'Landsize',
       'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude', 'Longtitude',
       'Regionname', 'Propertycount', 'id'],
      dtype='object')

In [134]:
test_new['Price'] = model.predict(test_new[X])

In [135]:
test_new.head()

,Suburb,Address,Rooms,Type,Method,SellerG,Date,Distance,Postcode,Bedroom2,...,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,id,Price
0,Abbotsford,513/6 Acacia Pl,3,u,S,Dingle,7/10/2017,3.0,3067.0,3.0,...,650.0,140.0,1970.0,Yarra City Council,-37.78290,145.02513,Northern Metropolitan,4019.0,30130,1.155140e+06
1,Abbotsford,60 Charles St,3,h,S,Jellis,7/10/2017,3.0,3067.0,3.0,...,192.0,109.0,1900.0,Yarra City Council,-37.80792,144.99508,Northern Metropolitan,4019.0,18311,1.461584e+06
2,Abbotsford,38 Studley St,3,h,S,Nelson,7/10/2017,3.0,3067.0,3.0,...,159.0,93.0,1890.0,Yarra City Council,-37.80124,144.99459,Northern Metropolitan,4019.0,18934,1.284623e+06
3,Airport West,18 Glenys Av,3,h,S,Raine,7/10/2017,10.4,3042.0,3.0,...,536.0,108.0,1980.0,Moonee Valley City Council,-37.72285,144.87539,Western Metropolitan,3464.0,1824,7.543415e+05
4,Airport West,35 Thomas St,3,h,S,Nelson,7/10/2017,10.4,3042.0,3.0,...,650.0,130.0,2009.0,Moonee Valley City Council,-37.71754,144.87704,Western Metropolitan,3464.0,31339,9.130536e+05

In [136]:
test_new[['id','Price']].to_csv('my_sub.csv', index=False)

In [137]:
test_ = pd.read_csv('D:/ds/leopard-challenge/my_sub.csv')

In [138]:
test_

         id         Price
0     30130  1.155140e+06
1     18311  1.461584e+06
2     18934  1.284623e+06
3      1824  7.543415e+05
4     31339  9.130536e+05
...     ...           ...
8813  11120  1.223123e+06
8814   3950  7.856465e+05
8815   2209  6.655786e+05
8816  23872  1.270856e+06
8817   8572  8.712813e+05

[8818 rows x 2 columns]